package-lock.json, package.json, public/index.html, src/App.js, src/components/Banner.css, src/components/Banner.js, src/components/PreLoader/PreLoader.js, src/components/ScrollDown/ScrollDown.css, src/components/ScrollDown/ScrollDown.js, src/components/SocialMedia/SocialMedia.css, src/components/SocialMedia/SocialMedia.js
=> Social Media Links Addition

src/App.css, src/components/NavBar.js, src/components/ScrollDown/ScrollDown.js, src/components/SocialMedia/SocialMedia.css, src/components/SocialMedia/SocialMedia.js, src/components/Sponsors.js
=> Social Links Url Update

src/components/NavBar.js
=> Brochure Link Update

package-lock.json, package.json, src/App.css, src/App.js, src/components/InstaDisplay/Feed.js, src/components/InstaDisplay/InstaFeeds.js, src/components/InstaDisplay/instaFeeds.css, src/components/PreLoader/PreLoader.css, src/components/PreLoader/PreLoader.js
Instagram Api Integration Update
=> Instagram Api Integration Update

src/App.js
=> Preloader TimeDelay Update

src/App.js, src/components/AppFeature/AppFeature.js, src/components/GeneralSponsorCard.css, src/components/GoldSponsorCard/GoldSponsorCard.css, src/components/MediumSponsorsCard.css, src/components/PreLoader/PreLoader.js, src/components/Sponsor.css, src/components/Sponsors.js
=> Preloader Video Update

src/App.js
=> App js Counter Update

src/components/Banner.js
=> Hackathon Countdown Update

src/components/Sponsor.css, src/components/Themes/Themes.css, src/components/Themes/Themes.js
Themes Card and Sponsor Dimension Update
=> Themes Card and Sponsor Dimension Update

public/index.html, src/App.js, src/PreloaderCode.txt, src/components/Banner.js, src/components/BannerText/BannerText.js, src/components/HackthonOverview.js
=> First Commit 2024

package.json, public/index.html, src/App.js, src/components/Schedule.js, src/components/Sponsors.js
ChatBot and Meta Keywords Update.
=> ChatBot and Meta Keywords Update.

src/globe.css, src/globe.js
=> Globe Component Update1

src/App.js, src/components/About.js, src/components/FaceGallery/Button.js, src/components/FaceGallery/FaceGallery.js, src/components/FaceGallery/Image.js, src/components/FaceGallery/ImageFilter.css, src/components/FaceGallery/ImageFilter.js, src/components/FaceGallery/PastGallery.txt, src/components/FaceGallery/Text.js, src/components/FaceGallery/filterableData.js
=> Gallery update1

src/App.js, src/components/CollegeClub/CollegeClub.css, src/components/CollegeClub/CollegeClub.js, src/components/FaceGallery/FaceGallery.js, src/components/FaceGallery/Image.css, src/components/FaceGallery/Image.js, src/components/FaceGallery/ImageFilter.css, src/components/FaceGallery/ImageFilter.js, src/components/FaceGallery/filterableData.js, src/components/GalleryLayout.js, src/components/MobileNavbar/MobileNavbar.js, src/components/NavBar.js, src/components/Schedule/Schedule.js
=> Gallery Component Changes

src/components/Background.css, src/components/Background.js, src/components/Banner.js, src/components/PastWinners/WinnerCard.js
=> Banner Update1

src/components/Background.css, src/components/Background.js
made different bg videos for mobile and video
=> fixed bg for all screens

src/components/FAQ/FAQs.js, src/components/FaceGallery/filterableData.js, src/components/Schedule/Schedule.js
=> Gallery Small Updates

src/components/Background.js
=> Bug fixes 1

src/components/Background.js, src/components/Banner.css
=> urgent Bug fixes 2

src/components/CollegeClub/CollegeClub.js, src/components/FAQ/FAQs.js, src/components/Schedule/Schedule.js
1. faqs and key dates fixed
2. glimpses image streching fixed
3. implemented lazy loading for glimpses
=> small changes faqs and more

src/App.js, src/components/GlobeNewComponent/GlobeNewComponent.js, src/components/MapChart/MapChart.css, src/components/MapChart/MapChart.js
MapChart New Component Update 2
=> MapChart New Component Update 2

src/App.js, src/components/CollegeClub/CollegeClub.js, src/components/NavBar.js
=> Gallery route change

src/components/Background.css, src/components/Background.js, src/components/Sponsors.js
=> Urgent Links Update

src/components/MapChart/MapChart.css, src/components/MapChart/MapChart.js
=> Mapchart  Update

src/components/Footer.js
=> Urgent Footer Links Update

src/components/Sponsors.js
=> Preloader Small update

LICENSE
=> MIT License Update

README.md
Readme Files Updates and Fixes
=> Readme Files Updates and Fixes

src/components/FAQ/FAQs.js
=> FAQ Minor function updates

src/App.js, src/components/GoldSponsorCard/GoldSponsorCard.css, src/components/InstagramReelsCards.js, src/components/MediumSponsorsCard.css, src/components/Schedule/Schedule.module.css
=> Small Updates

src/components/Background.js, src/components/reg-button.css
=> Register update

src/App.js
=> Themes update#02 rough

src/components/Sponsors.js, src/components/Teams/Teams.js, src/components/Teams/xyz.css
=> Sponsors update#03

src/App.js, src/components/Teams/Teams.js
=> Minor Changes#02

src/components/Sponsors.js
=> Minor Changes#03

src/components/Sponsors.js
=> Minor Changes#05

src/App.js, src/components/Teams/Teams.js
=> Minor Changes#07

src/App.js
=> Minor Changes#08

src/components/GalleryLayout.js, src/components/InstagramReelsCards.css, src/components/InstagramReelsCards.js
Added back to home button in the gallary section
=> Updated Gallary Section
